name: Deploy Basic Version

on:
  push:
    branches:
      - main  # Deploy saat ada perubahan di 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy Basic Version
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-basic  # Branch untuk Basic
          folder: Company Profile/Basic  # Folder yang akan dideploy
