name: Deploy Multiple Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy All Projects
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: company-profile
